package: io.mrarm.irc.config

AppSettings:
  import:
    - io.mrarm.irc.R
    - io.mrarm.irc.view.ChipsEditText
    - io.mrarm.irc.setting.ReconnectIntervalSetting
    - io.mrarm.irc.dialog.StorageLimitsDialog
    - java.util.List
  settings:
    - spec: String[] defaultNicks = new String[0]
      separator: io.mrarm.irc.view.ChipsEditText.SEPARATOR
    - spec: String defaultUser
    - spec: String defaultRealname
    - spec: String defaultQuitMessage = getContext().getString(R.string.pref_value_default_quit_message)
    - spec: String defaultPartMessage = getContext().getString(R.string.pref_value_default_part_message)

    - spec: boolean reconnectEnabled = true
    - spec: boolean reconnectWiFiOnly = false
      pref: reconnect_wifi
    - spec: boolean reconnectOnConnectivityChangeEnabled = true
      pref: reconnect_connchg
    - spec: String reconnectInterval
      pref: reconnect_interval
      getter: getReconnectIntervalString

    - spec: boolean pingEnabled = false
    - spec: boolean pingWiFiOnly = true
      pref: ping_wifi
    - spec: int pingInterval = 15 * 60 * 1000

    - spec: boolean drawerPinned = false
      setter: true

    - spec: String theme = "default_dark"
      setter: true

    - spec: long storageLimitGlobal = StorageLimitsDialog.DEFAULT_LIMIT_GLOBAL
    - spec: long storageLimitServer = StorageLimitsDialog.DEFAULT_LIMIT_SERVER
  helpers:
    - List<ReconnectIntervalSetting.Rule> getReconnectIntervalRules()

ChatSettings:
  pref_prefix: chat
  import:
    - android.graphics.Typeface
  settings:
    - spec: String font = "default"
      getter: getFontString
    - spec: int fontSize = 12
    - spec: boolean textAutocorrectEnabled = true
      pref: chat_text_autocorrect

    - spec: boolean hideJoinPartMessages = true
      getter: shouldHideJoinPartMessages
    - spec: String appbarCompactMode = "auto"
      enum: ["auto", "always", "never"]
    - spec: boolean sendBoxAlwaysMultiline = true
    - spec: boolean showDccSend = false
      getter: isDccSendVisible
  helpers:
    - Typeface getFont()
